### ISSUE TITLE
Webshell cant send commands

### ISSUE THREAD

**Issue by A-Lazar-A** [MythicAgents/arachne#2]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mythic_container/agent_utils.py", line 451, in createTasking
    createTaskingResponse = await cmd.create_go_tasking(taskData)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Mythic/arachne/agent_functions/ls.py", line 46, in create_go_tasking
    encrypted_resp = await SendMythicRPCCallbackEncryptBytes(MythicRPCCallbackEncryptBytesMessage(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mythic_container/MythicGoRPC/send_mythic_rpc_callback_encrypt_bytes.py", line 51, in SendMythicRPCCallbackEncryptBytes
    return MythicRPCCallbackEncryptBytesMessageResponse(**response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mythic_container/MythicGoRPC/send_mythic_rpc_callback_encrypt_bytes.py", line 42, in __init__
    self.Message = base64.b64decode(message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/base64.py", line 83, in b64decode
    s = _bytes_from_decode_data(s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType
```

**Comment by its-a-feature** [comment]
I pushed a fix for this the other day. Can you reinstall the agent and see if that fixes it for you? No need to generate a new payload or anything, it's just a server side issue due to an API change

**Comment by A-Lazar-A** [comment]
@its-a-feature Btw cookie name dosent required but without it server cant send request
```
[-] Failed to connect for WebShell: Illegal key ''
[-] Failed to connect for WebShell: Illegal key ''
```
